stages:
  - stage1
# stage
stage1:
  image: python:3.11-slim
  before_script:
    - apt-get update -qy
    - apt-get install -y curl jq wget xz-utils build-essential
  stage: stage1
  # script
  script:
    - make install
    - make lint
    - make format
